language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable"
    - php: 7.1
      env: COMPOSER_FLAGS=""
    - php: 7.1
      script: vendor/bin/phpcs -n
      env: PHPCS_BUILD=1

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
